openapi: 3.0.3
info:
  title: LottiesPeriod - Cycle Service API
  description: |
    API for tracking menstrual cycles and menstruation data.
    
    Terminology Guide:
    - Cycle: The entire reproductive timeframe (Example: 28 days). Starts on Day 1 of bleeding. Ends the day before the next bleeding event.
    - Menstruation: The specific phase of bleeding (Example: 5 days). This is a subset of the Cycle.

    **Authentication**: All endpoints require Bearer JWT token in Authorization header.
  version: 1.0.1
  contact:
    name: LottiesPeriod API Support

servers:
  - url: https://6463711e-6d80-462d-b8f5-630be77a4bfd.mock.pstmn.io/v1
    description: Postman Mock Server
  - url: https://api.lottiesperiod.com/v1
    description: Production server
  - url: https://staging-api.lottiesperiod.com/v1
    description: Staging server
  - url: http://localhost:8087/v1
    description: Local development server

tags:
  - name: Cycles
    description: Menstrual cycle management

security:
  - BearerAuth: []

paths:
  /cycles:
    get:
      tags:
        - Cycles
      summary: List cycles
      description: Retrieve cycle history for authenticated user
      parameters:
        - name: limit
          in: query
          description: Maximum number of cycles to return
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 12
        - name: offset
          in: query
          description: Number of cycles to skip
          schema:
            type: integer
            minimum: 0
            default: 0
        - name: status
          in: query
          description: Filter by cycle status
          schema:
            type: string
            enum:
              - ACTIVE
              - CLOSED
      responses:
        '200':
          description: List of cycles retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  cycles:
                    type: array
                    items:
                      $ref: '#/components/schemas/Cycle'
                  pagination:
                    $ref: '#/components/schemas/Pagination'
        '401':
          description: Unauthorized

    post:
      tags:
        - Cycles
      summary: Start a new Cycle (Log Start of Menstruation)
      description: |
        Triggers the start of a new Cycle.
        
        Logic: 
        1. This sets the Cycle Start Date.
        2. By definition, this is also the Menstruation (bleeding) Start Date.
        3. If a previous cycle is `ACTIVE`, it is automatically `CLOSED` with an end date of (`newStartDate` - 1 day).
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StartCycleRequest'
      responses:
        '201':
          description: Cycle started successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cycle'
        '400':
          description: Invalid date (e.g. in future)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /cycles/{cycleId}:
    get:
      tags:
        - Cycles
      summary: Get cycle by ID
      description: Retrieve a specific cycle with detailed information
      parameters:
        - name: cycleId
          in: path
          required: true
          description: Unique identifier of the cycle
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Cycle retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cycle'
        '404':
          description: Cycle not found

    patch:
      tags:
        - Cycles
      summary: Update cycle or menstruation details
      description: |
        Used to:
        1. Correct the `startDate` (if user forgot to log it on time).
        2. Set the `menstruationEndDate` (when bleeding stops).
      parameters:
        - name: cycleId
          in: path
          required: true
          description: Unique identifier of the cycle
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateCycleRequest'
      responses:
        '200':
          description: Cycle updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cycle'
        '400':
          description: Invalid data (e.g. menstruationEndDate before startDate)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'


  /cycles/current:
    get:
      tags:
        - Cycles
      summary: Get current active cycle
      responses:
        '200':
          description: Active cycle retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cycle'
        '404':
          description: No active cycle found

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Cycle:
      type: object
      description: Represents the full timeframe from one menstruation start to the next menstruation start.
      properties:
        id:
          type: string
          format: uuid
          example: "aa0e8400-e29b-41d4-a716-446655440005"
        userId:
          type: string
          format: uuid
          example: "550e8400-e29b-41d4-a716-446655440000"
        startDate:
          type: string
          format: date
          example: "2024-10-01"
          description: Day 1 of the Cycle. This is also Day 1 of bleeding.
        endDate:
          type: string
          format: date
          nullable: true
          example: "2024-10-28"
          description: The last day of the cycle (usually the day before next bleeding). Null if cycle is ACTIVE.

        menstruationEndDate:
          type: string
          format: date
          nullable: true
          example: "2024-10-05"
          description: The specific date bleeding stopped.
        menstruationLengthInDays:
          type: integer
          nullable: true
          example: 5
          description: Calculated duration of bleeding (StartDate -> MenstruationEndDate).

        cycleLengthInDays:
          type: integer
          nullable: true
          example: 28
          description: Total duration (From StartDate to EndDate). Null if cycle is ACTIVE.
        
        ovulationDate:
          type: string
          format: date
          nullable: true
          example: "2024-10-14"
          description: Predicted date of ovulation.
        
        status:
          type: string
          enum:
            - ACTIVE
            - CLOSED
          example: "CLOSED"
        currentPhase:
          type: string
          enum:
            - MENSTRUATION_PHASE
            - FOLLICULAR_PHASE
            - OVULATION_PHASE
            - LUTEAL_PHASE
          nullable: true
          example: "LUTEAL_PHASE"
          description: Calculated phase based on current date relative to start/ovulation dates.
        notes:
          type: string
          maxLength: 500
          nullable: true
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    StartCycleRequest:
      type: object
      required:
        - startDate
      properties:
        startDate:
          type: string
          format: date
          example: "2024-11-20"
          description: The day bleeding began.
        menstruationEndDate:
          type: string
          format: date
          nullable: false
          description: The day bleeding will stop/stopped. (If it's in the future, it is the predicted end date of bleeding.)
        notes:
          type: string
          maxLength: 500

    UpdateCycleRequest:
      type: object
      properties:
        startDate:
          type: string
          format: date
          description: Update if user misremembered the start day. Warning - Recalculates all cycle stats.
        menstruationEndDate:
          type: string
          format: date
          description: Set this when the user indicates bleeding has stopped.
        notes:
          type: string
          maxLength: 500

    Pagination:
      type: object
      properties:
        total:
          type: integer
          example: 12
        limit:
          type: integer
          example: 12
        offset:
          type: integer
          example: 0
        hasMore:
          type: boolean
          example: false

    Error:
      type: object
      properties:
        code:
          type: string
          example: "INVALID_DATE_SEQUENCE"
        message:
          type: string
          example: "Menstruation end date cannot be before cycle start date."
        details:
          type: object
          nullable: true
        timestamp:
          type: string
          format: date-time
          example: "2024-11-20T14:22:00Z"
