openapi: 3.0.3
info:
  title: LottiesPeriod - Health Data Integration API
  description: |
    Receives optional, consented health summaries from Apple HealthKit or Android Health Connect.
    Data is normalized and stored for integration with cycle predictions.
    
    **Authentication**: All endpoints require Bearer JWT token in Authorization header.
  version: 1.0.0
  contact:
    name: LottiesPeriod API Support

servers:
  - url: https://6463711e-6d80-462d-b8f5-630be77a4bfd.mock.pstmn.io/v1
    description: Postman Mock Server
  - url: https://api.lottiesperiod.com/v1
    description: Production server
  - url: https://staging-api.lottiesperiod.com/v1
    description: Staging server
  - url: http://localhost:8085/v1
    description: Local development server

tags:
  - name: Health Data
    description: Health data ingestion and retrieval
  - name: Sync
    description: Health data synchronization

security:
  - BearerAuth: []

paths:
  /health/data:
    post:
      tags:
        - Health Data
      summary: Upload health data samples
      description: |
        Upload health data samples from HealthKit or Android Health Connect.
        Samples are deduplicated, normalized, and aggregated into daily summaries.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HealthDataUploadRequest'
      responses:
        '201':
          description: Health data uploaded successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Health data uploaded successfully"
                  samplesProcessed:
                    type: integer
                    example: 15
                  samplesIgnored:
                    type: integer
                    example: 2
                    description: Samples ignored due to duplication
                  dailySummariesUpdated:
                    type: integer
                    example: 3
                    description: Number of daily summaries updated
        '400':
          description: Invalid health data format
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Health data consent not granted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /health/data/daily-summary:
    get:
      tags:
        - Health Data
      summary: Get daily health summaries
      description: Retrieve aggregated daily health summaries
      parameters:
        - name: startDate
          in: query
          description: Filter summaries from this date (inclusive)
          schema:
            type: string
            format: date
            example: "2024-11-01"
        - name: endDate
          in: query
          description: Filter summaries until this date (inclusive)
          schema:
            type: string
            format: date
            example: "2024-11-30"
        - name: limit
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 90
            default: 30
        - name: offset
          in: query
          schema:
            type: integer
            minimum: 0
            default: 0
      responses:
        '200':
          description: Daily summaries retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  summaries:
                    type: array
                    items:
                      $ref: '#/components/schemas/DailyHealthSummary'
                  pagination:
                    $ref: '#/components/schemas/Pagination'
        '400':
          description: Invalid query parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /health/data/daily-summary/{date}:
    get:
      tags:
        - Health Data
      summary: Get daily summary by date
      description: Retrieve health summary for a specific date
      parameters:
        - name: date
          in: path
          required: true
          description: Date in YYYY-MM-DD format
          schema:
            type: string
            format: date
            example: "2024-11-20"
      responses:
        '200':
          description: Daily summary retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DailyHealthSummary'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: No health data available for this date
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /health/sync/status:
    get:
      tags:
        - Sync
      summary: Get sync status
      description: Get the current health data synchronization status
      responses:
        '200':
          description: Sync status retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SyncStatus'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /health/sync/initiate:
    post:
      tags:
        - Sync
      summary: Initiate health data sync
      description: Request the mobile app to sync latest health data
      responses:
        '202':
          description: Sync request accepted
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Sync initiated successfully"
                  syncId:
                    type: string
                    format: uuid
                    example: "ff0e8400-e29b-41d4-a716-446655440010"
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Health data consent not granted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /health/data-types:
    get:
      tags:
        - Health Data
      summary: Get supported health data types
      description: List all supported health data types and their units
      responses:
        '200':
          description: Supported data types retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  dataTypes:
                    type: array
                    items:
                      $ref: '#/components/schemas/HealthDataType'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    HealthDataUploadRequest:
      type: object
      required:
        - source
        - samples
      properties:
        source:
          type: string
          enum:
            - APPLE_HEALTHKIT
            - ANDROID_HEALTH_CONNECT
          example: "APPLE_HEALTHKIT"
        samples:
          type: array
          minItems: 1
          maxItems: 1000
          items:
            $ref: '#/components/schemas/HealthSample'

    HealthSample:
      type: object
      required:
        - type
        - value
        - unit
        - startDate
        - endDate
        - sourceIdentifier
      properties:
        type:
          type: string
          enum:
            - HEART_RATE
            - RESTING_HEART_RATE
            - HEART_RATE_VARIABILITY
            - BODY_TEMPERATURE
            - BASAL_BODY_TEMPERATURE
            - SLEEP_HOURS
            - STEP_COUNT
            - ACTIVE_ENERGY
            - WEIGHT
          example: "BASAL_BODY_TEMPERATURE"
        value:
          type: number
          format: double
          example: 36.8
        unit:
          type: string
          example: "degC"
          description: Unit of measurement
        startDate:
          type: string
          format: date-time
          example: "2024-11-20T07:00:00Z"
        endDate:
          type: string
          format: date-time
          example: "2024-11-20T07:00:00Z"
        sourceIdentifier:
          type: string
          example: "com.apple.health.thermometer"
          description: Source app or device identifier
        deviceInfo:
          type: object
          nullable: true
          properties:
            name:
              type: string
              example: "Apple Watch Series 8"
            manufacturer:
              type: string
              example: "Apple"
            model:
              type: string
              example: "Watch6,2"
        metadata:
          type: object
          additionalProperties: true
          nullable: true
          description: Additional metadata from health platform

    DailyHealthSummary:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "gg0e8400-e29b-41d4-a716-446655440011"
        userId:
          type: string
          format: uuid
          example: "550e8400-e29b-41d4-a716-446655440000"
        date:
          type: string
          format: date
          example: "2024-11-20"
        metrics:
          type: object
          properties:
            basalBodyTemperature:
              type: object
              nullable: true
              properties:
                average:
                  type: number
                  format: float
                  example: 36.8
                min:
                  type: number
                  format: float
                  example: 36.5
                max:
                  type: number
                  format: float
                  example: 37.1
                unit:
                  type: string
                  example: "degC"
                sampleCount:
                  type: integer
                  example: 3
            heartRate:
              type: object
              nullable: true
              properties:
                average:
                  type: number
                  format: float
                  example: 72.5
                resting:
                  type: number
                  format: float
                  example: 65.0
                  nullable: true
                min:
                  type: number
                  format: float
                  example: 58.0
                max:
                  type: number
                  format: float
                  example: 142.0
                unit:
                  type: string
                  example: "bpm"
            sleepHours:
              type: object
              nullable: true
              properties:
                total:
                  type: number
                  format: float
                  example: 7.5
                deep:
                  type: number
                  format: float
                  nullable: true
                  example: 2.1
                rem:
                  type: number
                  format: float
                  nullable: true
                  example: 1.8
                unit:
                  type: string
                  example: "hr"
            stepCount:
              type: object
              nullable: true
              properties:
                total:
                  type: integer
                  example: 8543
                unit:
                  type: string
                  example: "count"
            activeEnergy:
              type: object
              nullable: true
              properties:
                total:
                  type: number
                  format: float
                  example: 425.3
                unit:
                  type: string
                  example: "kcal"
            weight:
              type: object
              nullable: true
              properties:
                value:
                  type: number
                  format: float
                  example: 65.2
                unit:
                  type: string
                  example: "kg"
        dataQuality:
          type: object
          properties:
            completeness:
              type: number
              format: float
              minimum: 0
              maximum: 1
              example: 0.85
              description: How complete the data is for this day
            sampleCount:
              type: integer
              example: 47
              description: Total number of raw samples
        createdAt:
          type: string
          format: date-time
          example: "2024-11-20T08:00:00Z"
        updatedAt:
          type: string
          format: date-time
          example: "2024-11-20T22:15:00Z"

    SyncStatus:
      type: object
      properties:
        userId:
          type: string
          format: uuid
          example: "550e8400-e29b-41d4-a716-446655440000"
        lastSyncAt:
          type: string
          format: date-time
          nullable: true
          example: "2024-11-20T08:30:00Z"
        lastSuccessfulSyncAt:
          type: string
          format: date-time
          nullable: true
          example: "2024-11-20T08:30:00Z"
        syncStatus:
          type: string
          enum:
            - NEVER_SYNCED
            - UP_TO_DATE
            - PENDING
            - IN_PROGRESS
            - FAILED
          example: "UP_TO_DATE"
        dataSource:
          type: string
          enum:
            - APPLE_HEALTHKIT
            - ANDROID_HEALTH_CONNECT
            - NONE
          nullable: true
          example: "APPLE_HEALTHKIT"
        oldestDataDate:
          type: string
          format: date
          nullable: true
          example: "2024-01-15"
        newestDataDate:
          type: string
          format: date
          nullable: true
          example: "2024-11-20"
        totalSamples:
          type: integer
          example: 1247
          description: Total health samples stored
        consentStatus:
          type: string
          enum:
            - GRANTED
            - DENIED
            - NOT_DETERMINED
          example: "GRANTED"

    HealthDataType:
      type: object
      properties:
        type:
          type: string
          example: "BASAL_BODY_TEMPERATURE"
        displayName:
          type: string
          example: "Basal Body Temperature"
        description:
          type: string
          example: "Body temperature measured immediately after waking"
        supportedUnits:
          type: array
          items:
            type: string
          example: ["degC", "degF"]
        category:
          type: string
          enum:
            - VITAL_SIGNS
            - ACTIVITY
            - BODY_MEASUREMENTS
            - SLEEP
          example: "VITAL_SIGNS"
        relevanceForCycleTracking:
          type: string
          enum:
            - HIGH
            - MEDIUM
            - LOW
          example: "HIGH"

    Pagination:
      type: object
      properties:
        total:
          type: integer
          example: 30
        limit:
          type: integer
          example: 30
        offset:
          type: integer
          example: 0
        hasMore:
          type: boolean
          example: false

    Error:
      type: object
      properties:
        code:
          type: string
          example: "CONSENT_REQUIRED"
        message:
          type: string
          example: "Health data consent must be granted before uploading data"
        details:
          type: object
          additionalProperties: true
          nullable: true
        timestamp:
          type: string
          format: date-time
          example: "2024-11-20T14:22:00Z"
